# Generated by Django 4.1 on 2023-04-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
