# Generated by Django 4.1 on 2023-04-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_categories_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
