# Generated by Django 4.1 on 2023-04-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_cartitem_line_total_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'quantity')},
        ),
    ]
