# Generated by Django 4.1 on 2023-04-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
