# Generated by Django 4.1 on 2023-05-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_cart_items_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
